"""Adds Orders Table

Revision ID: 640_add_orders_table
Revises: 630_Inoket
Create Date: 2016-06-24 17:50:27.894878

"""

# revision identifiers, used by Alembic.
revision = '640_add_orders_table'
down_revision = '630_Inoket'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('purchase_order_number', sa.String(length=256), nullable=True),
    sa.Column('amount_in_pennies', sa.Integer(), nullable=True),
    sa.Column('order_state', sa.Enum('received', name='order_states_enum'), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.execute('DROP TYPE order_states_enum')
    ### end Alembic commands ###
