"""Change orders.service_id to String

Revision ID: 650_change_service_id_datatype
Revises: 640_add_orders_table
Create Date: 2016-07-01 13:15:29.629574

"""

# revision identifiers, used by Alembic.
revision = '650_change_service_id_datatype'
down_revision = '640_add_orders_table'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'orders_service_id_fkey', 'orders', type_='foreignkey')
    op.alter_column('orders', 'service_id', type_=sa.String())
    op.create_foreign_key(None, 'orders', 'services', ['service_id'], ['service_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(u'orders_service_id_fkey', 'orders', 'services', ['service_id'], ['id'])
    ### end Alembic commands ###
